"""構造化テスト設計とケースを追加する。"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision = "6b7c8d9e0f1a"
down_revision = "5a6b7c8d9e0f"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='TestDesign: プロジェクト配下のテスト設計書。'
    )
    op.create_index(op.f('ix_test_designs_project_id'), 'test_designs', ['project_id'], unique=False)
    op.create_table('test_design_columns',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['test_designs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='TestDesignColumn: 任意列の定義。値は項目側で管理する。'
    )
    op.create_index(op.f('ix_test_design_columns_design_id'), 'test_design_columns', ['design_id'], unique=False)
    op.create_table('test_design_layouts',
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['test_designs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('design_id'),
    comment='TestDesignLayout: セル書式と寸法。業務データとは別テーブルで保存する。'
    )
    op.create_table('test_factors',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['test_designs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_id', 'id'),
    comment='Factor: 組み合わせを構成する因子。'
    )
    op.create_index(op.f('ix_test_factors_design_id'), 'test_factors', ['design_id'], unique=False)
    op.create_table('test_items',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('viewpoint', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('preconditions', sa.Text(), nullable=False),
    sa.Column('test_data', sa.Text(), nullable=False),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('custom_values', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['test_designs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_id', 'id'),
    comment='TestItem: テスト項目。固定項目と拡張列の値を保持する。'
    )
    op.create_index(op.f('ix_test_items_design_id'), 'test_items', ['design_id'], unique=False)
    op.create_table('test_patterns',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['test_designs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_id', 'id'),
    comment='TestPattern: 再利用可能な組み合わせ。'
    )
    op.create_index(op.f('ix_test_patterns_design_id'), 'test_patterns', ['design_id'], unique=False)
    op.create_table('test_factor_levels',
    sa.Column('factor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['design_id', 'factor_id'], ['test_factors.design_id', 'test_factors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['design_id'], ['test_designs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_id', 'factor_id', 'id'),
    comment='FactorLevel: 因子に属する水準。'
    )
    op.create_index(op.f('ix_test_factor_levels_design_id'), 'test_factor_levels', ['design_id'], unique=False)
    op.create_table('test_item_patterns',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('pattern_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['design_id', 'item_id'], ['test_items.design_id', 'test_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['design_id', 'pattern_id'], ['test_patterns.design_id', 'test_patterns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['design_id'], ['test_designs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_id', 'item_id', 'pattern_id'),
    comment='TestItemPattern: 項目とパターンの多対多関連。'
    )
    op.create_index(op.f('ix_test_item_patterns_design_id'), 'test_item_patterns', ['design_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('item_pattern_id', sa.Uuid(), nullable=True),
    sa.Column('source', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('actual_result', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['test_designs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_pattern_id'], ['test_item_patterns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_pattern_id'),
    comment='TestCase: 生成時の内容と個別の実行結果を持つテストケース。'
    )
    op.create_index(op.f('ix_test_cases_design_id'), 'test_cases', ['design_id'], unique=False)
    op.create_table('test_pattern_values',
    sa.Column('pattern_id', sa.Uuid(), nullable=False),
    sa.Column('factor_id', sa.Uuid(), nullable=False),
    sa.Column('level_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['design_id', 'factor_id', 'level_id'], ['test_factor_levels.design_id', 'test_factor_levels.factor_id', 'test_factor_levels.id'], ),
    sa.ForeignKeyConstraint(['design_id', 'factor_id'], ['test_factors.design_id', 'test_factors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['design_id', 'pattern_id'], ['test_patterns.design_id', 'test_patterns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['design_id'], ['test_designs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_id', 'pattern_id', 'factor_id'),
    comment='TestPatternValue: パターン内で選択した水準。nullは対象外を表す。'
    )
    op.create_index(op.f('ix_test_pattern_values_design_id'), 'test_pattern_values', ['design_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    op.drop_table('test_pattern_values')
    op.drop_table('test_cases')
    op.drop_table('test_item_patterns')
    op.drop_table('test_factor_levels')
    op.drop_table('test_patterns')
    op.drop_table('test_items')
    op.drop_table('test_factors')
    op.drop_table('test_design_layouts')
    op.drop_table('test_design_columns')
    op.drop_table('test_designs')
