"""パターンの期待値を独立管理する。"""

from alembic import op
import sqlalchemy as sa

revision = "7c8d9e0f1a2b"
down_revision = "6b7c8d9e0f1a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_expected_values",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("design_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["design_id"], ["test_designs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("design_id", "id"),
        comment="ExpectedValue: 因子とは独立した期待値の候補。",
    )
    op.create_index(
        op.f("ix_test_expected_values_design_id"),
        "test_expected_values",
        ["design_id"],
        unique=False,
    )
    op.create_table(
        "test_pattern_expected_values",
        sa.Column("pattern_id", sa.Uuid(), nullable=False),
        sa.Column("expected_value_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("design_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["design_id", "expected_value_id"],
            ["test_expected_values.design_id", "test_expected_values.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["design_id", "pattern_id"],
            ["test_patterns.design_id", "test_patterns.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["design_id"], ["test_designs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("design_id", "pattern_id"),
        comment="TestPatternExpectedValue: パターンが選択した期待値。",
    )
    op.create_index(
        op.f("ix_test_pattern_expected_values_design_id"),
        "test_pattern_expected_values",
        ["design_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("test_pattern_expected_values")
    op.drop_table("test_expected_values")
